### ISSUE TITLE
Nullable object must have value

### ISSUE THREAD

**Issue by martinrayenglish** [Antonytm/Sitecore.Lighthouse#1]
When clicking on the "Run" action, the following error is thrown:
![image-2020-09-04-13-53-17-133](https://user-images.githubusercontent.com/3728669/92780216-6e3f1e00-f368-11ea-950b-c792e6ce5dc6.png)

This issue is caused by spaces in the url argument. Simply adding quotes around it fixes the issue.
Example: lighthouse https://example.com/bob wins 
Should be: lighthouse "https://example.com/bob wins"

**Comment by Antonytm** [comment]
Thank you for reporting this issue, I will fix it.

**Comment by Antonytm** [comment]
Fixed in latest release
